// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered favicon variation generator.
 *
 * - generateFaviconVariations - Generates favicon variations based on a given input favicon.
 * - GenerateFaviconVariationsInput - The input type for the generateFaviconVariations function.
 * - GenerateFaviconVariationsOutput - The return type for the generateFaviconVariations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFaviconVariationsInputSchema = z.object({
  faviconDataUri: z
    .string()
    .describe(
      'A favicon, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.' // Corrected typo here
    ),
  numVariations: z
    .number()
    .default(3)
    .describe('The number of variations to generate.'),
});
export type GenerateFaviconVariationsInput = z.infer<
  typeof GenerateFaviconVariationsInputSchema
>;

const GenerateFaviconVariationsOutputSchema = z.object({
  variations: z.array(
    z.object({
      imageDataUri: z
        .string()
        .describe(
          'A variation of the favicon, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'
        ),
    })
  ),
});
export type GenerateFaviconVariationsOutput = z.infer<
  typeof GenerateFaviconVariationsOutputSchema
>;

export async function generateFaviconVariations(
  input: GenerateFaviconVariationsInput
): Promise<GenerateFaviconVariationsOutput> {
  return generateFaviconVariationsFlow(input);
}

const generateFaviconVariationsPrompt = ai.definePrompt({
  name: 'generateFaviconVariationsPrompt',
  input: {schema: GenerateFaviconVariationsInputSchema},
  output: {schema: GenerateFaviconVariationsOutputSchema},
  prompt: `You are an expert favicon designer. Given the following favicon, generate {{numVariations}} variations with subtly altered colors or shapes to provide additional options and spark inspiration.

Original Favicon: {{media url=faviconDataUri}}

Variations:`, // Corrected media url handlebars
});

const generateFaviconVariationsFlow = ai.defineFlow(
  {
    name: 'generateFaviconVariationsFlow',
    inputSchema: GenerateFaviconVariationsInputSchema,
    outputSchema: GenerateFaviconVariationsOutputSchema,
  },
  async input => {
    const {output} = await generateFaviconVariationsPrompt(input);
    return output!;
  }
);
